### ISSUE TITLE
Move to Rails org

### ISSUE THREAD

**Issue by josh** [rails/ruby-coffee-script#1]
Todos for completing this transition.
- [x] Review maintaining documentation under Rails org
- [x] Give gem publish access to rails core https://rubygems.org/gems/coffee-script
- [x] Give gem publish access to rails core https://rubygems.org/gems/coffee-script-source
- [x] Document and add scripts for coffee-script-source release process
- [x] Enable Travis

/cc @rafaelfranca

**Comment by josh** [comment]
@rafaelfranca is there a set of emails that should have push access to all rails related gems?

**Comment by rafaelfranca** [comment]
``` ruby
#!/usr/bin/env ruby
EMAILS = %w(
aaron.patterson@gmail.com
andyw@pixeltrix.co.uk
carlosantoniodasilva@gmail.com
david@loudthinking.com
fxn@hashref.com
godfreykfc@gmail.com
guilleiguaran@gmail.com
jeremy@bitsweat.net
jose.valim@gmail.com
michael@koziarski.com
rafaelmfranca@gmail.com
santiago@wyeworks.com
yves.senn@gmail.com
)

gem = ARGV[0]
EMAILS.each do |email|
  print "Adding #{email} as owner of #{gem}... "
  `gem owner #{gem} -a #{email}`
  puts "OK"
end
```

**Comment by josh** [comment]
haha, in executable form. :heart:

**Comment by josh** [comment]
Alright, this repository should be all set. @rafaelfranca let me know if theres anything else. Thanks!
