### ISSUE TITLE
Question: How about CoffeeScript v1.12.1?

### ISSUE THREAD

**Issue by junaruga** [rails/ruby-coffee-script#11]
Right now rubygem coffee-script-source's latest version is 1.11.1.
https://rubygems.org/gems/coffee-script-source

coffee-script latest version is 1.12.1
http://coffeescript.org/#1.12.1
1.12.1 — December 8, 2016

**Comment by guilleiguaran** [comment]
Unfortunately I was able to build the new version of coffee-script locally so I can't publish it to rubygems:

```
./script/build-source-gem 1.12.1
+ VERSION=1.12.1
+ mkdir -p tmp/
+ pushd tmp/
~/src/ruby-coffee-script/tmp ~/src/ruby-coffee-script
+ '[' '!' -d coffeescript/ ']'
+ pushd coffeescript/
~/src/ruby-coffee-script/tmp/coffeescript ~/src/ruby-coffee-script/tmp ~/src/ruby-coffee-script
+ git checkout 1.12.1
M	docs/v1/browser-compiler/coffee-script.js
HEAD is now at 26cfd19... Update 1.12.1 release date
+ npm install
+ mkdir -p lib/coffee_script
+ MINIFY=false
+ cake build:browser
built ... running browser tests:
/Users/guille/src/ruby-coffee-script/tmp/coffeescript/Cakefile:318
    CoffeeScript.register();
                ^

TypeError: Cannot read property 'register' of undefined
  at runTests (/Users/guille/src/ruby-coffee-script/tmp/coffeescript/Cakefile:318:17)
  at Object.action (/Users/guille/src/ruby-coffee-script/tmp/coffeescript/Cakefile:408:12)
  at invoke (/usr/local/lib/node_modules/cake/lib/cake.js:44:26)
  at Object.action (/Users/guille/src/ruby-coffee-script/tmp/coffeescript/Cakefile:140:12)
  at invoke (/usr/local/lib/node_modules/cake/lib/cake.js:44:26)
  at Object.exports.run (/usr/local/lib/node_modules/cake/lib/cake.js:70:21)
  at Object.<anonymous> (/usr/local/lib/node_modules/cake/bin/cake:7:32)
  at Module._compile (module.js:573:32)
  at Object.Module._extensions..js (module.js:582:10)
  at Module.load (module.js:490:32)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.runMain (module.js:607:10)
  at run (bootstrap_node.js:382:7)
  at startup (bootstrap_node.js:137:9)
  at bootstrap_node.js:497:3
```

**Comment by guilleiguaran** [comment]
ok, published: https://rubygems.org/gems/coffee-script-source/versions/1.12.1

**Comment by junaruga** [comment]
Thanks, @guilleiguaran !

**Comment by junaruga** [comment]
@guilleiguaran 

I have found one thing.
Below date should be actual uploaded date(= today = December 15 2016)?

https://rubygems.org/gems/coffee-script-source/versions/1.12.1

> 1.12.1 - December 8, 2016 (4.5 KB)

**Comment by rafaelfranca** [comment]
I released it at that date

**Comment by jhawthorn** [comment]
@guilleiguaran @rafaelfranca The latest version of the `coffee-script-source` gem is broken (basically empty).


```
$ gem fetch coffee-script-source
Fetching: coffee-script-source-1.12.1.gem (100%)
Downloaded coffee-script-source-1.12.1
$ tar xvf coffee-script-source-1.12.1.gem
metadata.gz
data.tar.gz
checksums.yaml.gz
$ tar xvf data.tar.gz
lib/coffee_script/coffee-script.js
lib/coffee_script/source.rb
$ cat lib/coffee_script/coffee-script.js
/**
 * CoffeeScript Compiler v1.12.1
 * http://coffeescript.org
 *
 * Copyright 2011, Jeremy Ashkenas
 * Released under the MIT License
 */
undefined
```

The `1.12.1` gem should probably be yanked.

**Comment by sechix** [comment]
Hi, Sorry but continue with the same error. When download  coffee-script-source, it download Downloaded coffee-script-source-1.11.1 version, maybe that is the reason. I have tried to find 1.12.1 but is missing

**Comment by rafaelfranca** [comment]
Can you uninstall all the coffee-script-source gems you have?. 1.12.1 is not available anymore

**Comment by sechix** [comment]
Sorry i don't understand. I need to uninstall all coffee-script in order to solve the problem, not follow jhawthorn instructions?
In my gemfile I have this:
# # Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.2'

I have also to delete it ? because in the gemfile.lock I have dependencies between them:
    coffee-rails (4.2.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.2.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.1)

**Comment by guilleiguaran** [comment]
@sechix I've released a new version of coffee-script-source https://rubygems.org/gems/coffee-script-source/versions/1.12.2, you can use that version

**Comment by sechix** [comment]
Perfect, thanks @guilleiguaran It solved the issue. One question, You know if there is a marketplace extension available for solidus ? Because the one in github is missing.
