### ISSUE TITLE
Broken coffee-script-source gem 1.12.1

### ISSUE THREAD

**Issue by haberbyte** [rails/ruby-coffee-script#13]
Hope this is the right place to file this issue.

The coffees-script-source gem 1.12.1 is only 4kb in size because the actual coffee-script compiler js  code is missing in the gem.

Contents of coffee-script.js:
```
/**
 * CoffeeScript Compiler v1.12.1
 * http://coffeescript.org
 *
 * Copyright 2011, Jeremy Ashkenas
 * Released under the MIT License
 */
undefined
```

<img width="701" alt="screen shot 2016-12-15 at 21 16 12" src="https://cloud.githubusercontent.com/assets/7480/21240585/33eeb9c6-c30c-11e6-90b1-0082506468cc.png">

**Comment by StevenClontz** [comment]
That empty version seems to have been removed as of this comment: https://rubygems.org/gems/coffee-script-source/

**Comment by guilleiguaran** [comment]
coffee-script-source 1.12.1 was yanked

Looks like our automated script to build a wrong version of the gem due to the problem described in https://github.com/jashkenas/coffeescript/issues/4403

**Comment by haberbyte** [comment]
Yep. Fixed it in https://github.com/jashkenas/coffeescript/pull/4404

**Comment by guilleiguaran** [comment]
I've released a new version of coffee-script-source https://rubygems.org/gems/coffee-script-source/versions/1.12.2
