### ISSUE TITLE
Rubygems coffee-script-source SOURCE link

### ISSUE THREAD

**Issue by junaruga** [rails/ruby-coffee-script#16]
It is possible to add this github repository's URL [1] to RubyGems coffee-script-source's page SOURCE link [2]?
Because it was hard for me to find it in my past time.

Thanks.

[1] https://github.com/rails/ruby-coffee-script
[2] https://rubygems.org/gems/coffee-script-source

**Comment by rafaelfranca** [comment]
The source for that gem is the coffeescript source and it is linked as codebase. We can't link to this repository.
