### ISSUE TITLE
Wrong RubyGems coffee-script page links?

### ISSUE THREAD

**Issue by junaruga** [rails/ruby-coffee-script#17]
Hi,

"Homepage" and "Source Code" links in the RubyGems "coffee-script" page [1] are `josh/ruby-coffee-script` [2].
But [2] looks older than this github URL `rails/ruby-coffee-script` [3].
Which is correct URL?

[1] https://rubygems.org/gems/coffee-script
[2] https://github.com/josh/ruby-coffee-script
[3] https://github.com/rails/ruby-coffee-script

**Comment by matthewd** [comment]
Thanks for the report.

I've fixed the secondary URLs on rubygems.org. The Homepage link will be updated when a new release gets pushed (#3).
