### ISSUE TITLE
Please use version bounds

### ISSUE THREAD

**Issue by GeoffreyBooth** [rails/ruby-coffee-script#19]
[CoffeeScript 2](http://coffeescript.org/v2/) is coming, and it will be a breaking-change release of CoffeeScript that outputs ES2015 syntax. Code intended for browsers will need to be further processed by Babel or a similar tool.

It looks to me like this gem pulls in CoffeeScript by simply pulling the latest from the `master` branch on https://github.com/jashkenas/coffeescript/. This seems brittle, to say the least; if 2.0.0 gets merged into `master`, this gem will suddenly break.

I suggest that instead of `git clone`ing the repo, you use `npm install` and pull a specific version or version bound, e.g. `npm install coffeescript@1.x` to get the latest 1.x version but not 2.x.

**Comment by rafaelfranca** [comment]
Thank you for the issue. We don't pull the latest commit from master. We only release the code in the tagged releases of the coffeescript repository.
