### ISSUE TITLE
[Request/Question]: CoffeeScript 2 Beta Support?

### ISSUE THREAD

**Issue by MutableLoss** [rails/ruby-coffee-script#20]
I'm curious if there are any plans to offer a beta branch/release anytime soon with CS2 support?

**Comment by kWhittington** [comment]
Pretty please.

**Comment by joeldrapper** [comment]
This issue should probably be closed since CoffeeScript2 is no longer in beta. 🎉

**Comment by MutableLoss** [comment]
I think you're mis-reading the title, but it looks like the change was made 14 days ago for ruby-coffee-script. 🎉 

https://github.com/rails/ruby-coffee-script/tree/master/script

No need for a beta package, as ruby-coffee-script now supports 1 and 2, without the need for a new version it seems.
